name: Frontend CI/CD (Development)

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    environment: Development
    runs-on: ubuntu-latest

    steps:
      ############################################################
      # Checkout
      ############################################################
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check OIDC Token Availability
        run: |
          echo "ACTIONS_ID_TOKEN_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN=${ACTIONS_ID_TOKEN_REQUEST_TOKEN:+SET}"

      ############################################################
      # Configure AWS Credentials
      ############################################################
      - name: Debug GitHub Context
        run: |
          echo "Repository : ${{ github.repository }}"
          echo "Ref        : ${{ github.ref }}"
          echo "Ref Name   : ${{ github.ref_name }}"
          echo "Environment: ${{ github.environment }}"
          echo "Role ARN   : ${{ secrets.AWS_ROLE_ARN }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      ############################################################
      # Upload Frontend to S3
      ############################################################
      - name: Upload Files to Amazon S3
        run: |
          aws s3 sync frontend/ s3://${{ vars.S3_BUCKET_NAME }} \
            --delete

      ############################################################
      # CloudFront Cache Invalidation
      ############################################################
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"