name: Frontend CI/CD (Development)

on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    environment:
      name: Development

    steps:

      ############################################################
      # CHECKOUT
      ############################################################

      - name: Checkout Repository
        uses: actions/checkout@v4

      ############################################################
      # CONFIGURE AWS CREDENTIALS
      ############################################################

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: github-actions-frontend

      ############################################################
      # VERIFY AWS LOGIN
      ############################################################

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity


      ############################################################
      # DEPLOY TO S3
      ############################################################

      - name: Upload Frontend to Amazon S3
        run: |
          aws s3 sync frontend/ s3://${{ vars.S3_BUCKET_NAME }} --delete

      ############################################################
      # INVALIDATE CLOUDFRONT
      ############################################################

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"